### ISSUE TITLE
Java 1.8 compiled classes are not supported?

### ISSUE THREAD

**Issue by zolyfarkas** [francisdb/serviceloader-maven-plugin#14]
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:179)
	... 20 more
Caused by: java.lang.UnsupportedClassVersionError: com.company.Clasz$1 : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at eu.somatik.maven.serviceloader.ServiceloaderMojo.findImplementations(ServiceloaderMojo.java:215)
	at eu.somatik.maven.serviceloader.ServiceloaderMojo.execute(ServiceloaderMojo.java:123)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)

**Comment by zolyfarkas** [comment]
Was running maven with java 1.7, and compiling with java 1.8...
Running maven with java 1.8 fixes the issue...

**Comment by francisdb** [comment]
Thanks for logging this :-)
